from django.contrib.auth.decorators import login_required
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('app_page/', views.AllAppView.as_view(), name='app_page'),
    path('', views.get_home_view, name='homepage'),
    path('categories/<str:cat>', views.get_category_filter, name='categories'),
    path('search/', views.search, name='search'),
    path('increasing_price/', views.IncreasingPriceView.as_view(),
         name='price_increasing'),
    path('decreasing_price/', views.DecreasingPriceView.as_view(),
         name='price_decreasing'),
    path('apps_ios/', views.IOSDevicesView.as_view(), name='apps_ios'),
    path('apps_android/', views.AndroidDevicesView.as_view(), name='apps_android'),
    path('user_app_page/<slug>',
         views.UserAppDetailView.as_view(), name='user_app_view'),
    path('user/<username>/', views.get_user_profile_view, name='user_profile'),
    path('otheruser/<username>/', views.get_other_profile_view,
         name='otheruser_profile'),
    path('user/user_purchases',
         login_required(views.PurchasesView.as_view()), name='user_purchases'),
    path('add_app/', login_required(views.AddAppView.as_view()), name='add_app'),
    path('user/<username>/user_sales/',
         login_required(views.get_sales_view), name='user_sales'),
    path('user/<username>/address_page/',
         login_required(views.address_view), name='address_page'),
    path('user/address/<int:pk>/',
         login_required(views.address_detail), name='address'),
    path('user/address/<int:pk>/delete/',
         login_required(views.AddressDeleteView.as_view()), name='address_delete'),
    path('user/address/<int:pk>/modify/',
         login_required(views.AddressChangeView.as_view()), name='address_modify'),
    path('user/<username>/sales_graph/',
         login_required(views.sales_graph), name='sales_graph'),
    path('product/<slug>', views.AppDetailView.as_view(), name='app_view'),
    path('app/<int:pk>/delete/',
         login_required(views.AppDeleteView.as_view()), name='app_delete'),
    path('app/<int:pk>/modify/',
         login_required(views.AppModifyView.as_view()), name='app_modify'),
    path('app/<int:pk>/rate/',
         login_required(views.AppRaitingView.as_view()), name='app_rate'),
    path('add_to_cart/<slug>', login_required(views.add_to_cart), name='add_to_cart'),
    path('remove_from_cart/<slug>',
         login_required(views.remove_from_cart), name='remove_from_cart'),
    path('order_summary/', login_required(views.OrderSummaryView.as_view()),
         name='order_summary'),
    path('checkout/', login_required(views.CheckoutView.as_view()), name='checkout'),
    path('order_display/<pk>',
         login_required(views.OrderDisplayView.as_view()), name='order_display'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
